export const STAGES = new Map ([
  ['PRELIMINARY_ROUND','PRELIMINARY ROUND'],
  ['REGULAR_SEASON', 'REGULAR SEASON'],
  ['QUALIFICATION_ROUND_1', 'QUALIFICATION ROUND 1'],
  ['QUALIFICATION_ROUND_2', 'QUALIFICATION ROUND 2'],
  ['QUALIFICATION_ROUND_3', 'QUALIFICATION ROUND 3'],
  ['1ST_QUALIFYING_ROUND', '1ST QUALIFYING ROUND'],
  ['2ND_QUALIFYING_ROUND', '2ND QUALIFYING ROUND'],
  ['3RD_QUALIFYING_ROUND', '3RD QUALIFYING ROUND'],
  ['PLAY_OFF_ROUND', 'PLAY OFF ROUND'],
  ['GROUP_STAGE', 'GROUP STAGE'],
  ['ROUND_OF_16', 'ROUND OF 16'],
  ['LAST_16', 'LAST 16'],
  ['QUARTER_FINALS', 'QUARTER FINALS'],
  ['3RD_PLACE', '3RD PLACE'],
  ['SEMI_FINALS', 'SEMI FINALS'],
  ['FINAL', 'FINAL'],
])

export const STATUS = new Map ([
  ['SCHEDULED', 'SCHEDULED'],
  ['POSTPONED', 'POSTPONED'],
  ['CANCELED', 'CANCELED'],
  ['SUSPENDED', 'SUSPENDED'],
  ['IN_PLAY', 'IN PLAY'],
  ['PAUSED', 'PAUSED'],
  ['AWARDED', 'AWARDED'],
  ['FINISHED', 'FINISHED'],
])